// ─────────────────────────────────────────────────────────────────────────────
// Template Registry — Maps document types to their available sections, default
// configurations, reference code prefixes, and display metadata.
// ─────────────────────────────────────────────────────────────────────────────

import type { DocumentType, SectionType, DocumentSectionData } from "./types";

export interface DocumentTypeConfig {
  type: DocumentType;
  name: string;
  label: string;
  shortLabel: string;
  codePrefix: string;
  description: string;
  icon: string; // lucide icon name
  hasBOQ: boolean;
  hasTimeline: boolean;
  hasGallery: boolean;
  hasSignatures: boolean;
  hasQR: boolean;
  defaultSections: SectionType[];
  supportedSections: SectionType[];
  color: string;
}

export const DOCUMENT_TYPE_CONFIGS: Record<DocumentType, DocumentTypeConfig> = {
  QUOTATION: {
    type: "QUOTATION",
    name: "Quotation",
    label: "Quotation",
    shortLabel: "QT",
    codePrefix: "QT",
    description: "Commercial quotation with itemized pricing",
    icon: "FileText",
    hasBOQ: true,
    hasTimeline: true,
    hasGallery: true,
    hasSignatures: true,
    hasQR: true,
    defaultSections: ["cover", "client", "company_profile", "terms", "boq", "services", "timeline", "signatures", "qr"],
    supportedSections: ["cover", "client", "company_profile", "terms", "boq", "services", "timeline", "signatures", "qr"],
    color: "#3b82f6",
  },
  TAX_INVOICE: {
    type: "TAX_INVOICE",
    name: "Tax Invoice",
    label: "Tax Invoice",
    shortLabel: "INV",
    codePrefix: "INV",
    description: "GST-compliant tax invoice",
    icon: "Receipt",
    hasBOQ: true,
    hasTimeline: false,
    hasGallery: false,
    hasSignatures: true,
    hasQR: true,
    defaultSections: ["cover", "client", "boq", "terms", "signatures", "qr"],
    supportedSections: ["cover", "client", "boq", "terms", "signatures", "qr"],
    color: "#10b981",
  },
  PROFORMA_INVOICE: {
    type: "PROFORMA_INVOICE",
    name: "Proforma Invoice",
    label: "Proforma Invoice",
    shortLabel: "PI",
    codePrefix: "PI",
    description: "Pre-shipment invoice for advance billing",
    icon: "FileSpreadsheet",
    hasBOQ: true,
    hasTimeline: false,
    hasGallery: false,
    hasSignatures: true,
    hasQR: true,
    defaultSections: ["cover", "client", "boq", "terms", "signatures", "qr"],
    supportedSections: ["cover", "client", "boq", "terms", "signatures", "qr"],
    color: "#06b6d4",
  },
  PURCHASE_ORDER: {
    type: "PURCHASE_ORDER",
    name: "Purchase Order",
    label: "Purchase Order",
    shortLabel: "PO",
    codePrefix: "PO",
    description: "Material or service purchase order",
    icon: "ShoppingCart",
    hasBOQ: true,
    hasTimeline: false,
    hasGallery: false,
    hasSignatures: true,
    hasQR: false,
    defaultSections: ["cover", "client", "boq", "terms", "signatures"],
    supportedSections: ["cover", "client", "boq", "terms", "signatures"],
    color: "#8b5cf6",
  },
  WORK_ORDER: {
    type: "WORK_ORDER",
    name: "Work Order",
    label: "Work Order",
    shortLabel: "WO",
    codePrefix: "WO",
    description: "Project work order with scope and timeline",
    icon: "Hammer",
    hasBOQ: true,
    hasTimeline: true,
    hasGallery: false,
    hasSignatures: true,
    hasQR: true,
    defaultSections: ["cover", "client", "project", "scope_of_work", "boq", "timeline", "terms", "signatures", "qr"],
    supportedSections: ["cover", "client", "project", "scope_of_work", "boq", "timeline", "terms", "signatures", "qr"],
    color: "#f59e0b",
  },
  SITE_VISIT_REPORT: {
    type: "SITE_VISIT_REPORT",
    name: "Site Visit Report",
    label: "Site Visit Report",
    shortLabel: "SVR",
    codePrefix: "SVR",
    description: "Field site inspection and assessment report",
    icon: "MapPin",
    hasBOQ: false,
    hasTimeline: false,
    hasGallery: true,
    hasSignatures: true,
    hasQR: false,
    defaultSections: ["cover", "client", "project", "gallery", "signatures"],
    supportedSections: ["cover", "client", "project", "gallery", "signatures"],
    color: "#ef4444",
  },
  BOREWELL_COMPLETION_REPORT: {
    type: "BOREWELL_COMPLETION_REPORT",
    name: "Borewell Completion Report",
    label: "Borewell Completion Report",
    shortLabel: "BCR",
    codePrefix: "BCR",
    description: "Borewell drilling completion and test report",
    icon: "Drill",
    hasBOQ: false,
    hasTimeline: true,
    hasGallery: true,
    hasSignatures: true,
    hasQR: true,
    defaultSections: ["cover", "client", "project", "methodology", "timeline", "gallery", "technical_drawings", "signatures", "qr"],
    supportedSections: ["cover", "client", "project", "methodology", "timeline", "gallery", "technical_drawings", "signatures", "qr"],
    color: "#64748b",
  },
  RWH_REPORT: {
    type: "RWH_REPORT",
    name: "Rainwater Harvesting Report",
    label: "Rainwater Harvesting Report",
    shortLabel: "RWH",
    codePrefix: "RWH",
    description: "Rainwater harvesting system installation report",
    icon: "CloudRain",
    hasBOQ: false,
    hasTimeline: true,
    hasGallery: true,
    hasSignatures: true,
    hasQR: true,
    defaultSections: ["cover", "client", "project", "methodology", "timeline", "gallery", "signatures", "qr"],
    supportedSections: ["cover", "client", "project", "methodology", "timeline", "gallery", "signatures", "qr"],
    color: "#0ea5e9",
  },
  HYDROGEO_SURVEY: {
    type: "HYDROGEO_SURVEY",
    name: "Hydrogeological Survey Report",
    label: "Hydrogeological Survey Report",
    shortLabel: "HGS",
    codePrefix: "HGS",
    description: "Groundwater survey and geological assessment",
    icon: "Search",
    hasBOQ: false,
    hasTimeline: false,
    hasGallery: true,
    hasSignatures: true,
    hasQR: true,
    defaultSections: ["cover", "client", "project", "methodology", "gallery", "technical_drawings", "signatures", "qr"],
    supportedSections: ["cover", "client", "project", "methodology", "gallery", "technical_drawings", "signatures", "qr"],
    color: "#0d9488",
  },
  TECHNICAL_PROPOSAL: {
    type: "TECHNICAL_PROPOSAL",
    name: "Technical Proposal",
    label: "Technical Proposal",
    shortLabel: "TP",
    codePrefix: "TP",
    description: "Detailed technical solution proposal",
    icon: "Cpu",
    hasBOQ: true,
    hasTimeline: true,
    hasGallery: true,
    hasSignatures: true,
    hasQR: true,
    defaultSections: ["cover", "client", "project", "scope_of_work", "methodology", "services", "boq", "timeline", "gallery", "signatures", "qr"],
    supportedSections: ["cover", "client", "project", "scope_of_work", "methodology", "services", "boq", "timeline", "gallery", "signatures", "qr"],
    color: "#6366f1",
  },
  COMMERCIAL_PROPOSAL: {
    type: "COMMERCIAL_PROPOSAL",
    name: "Commercial Proposal",
    label: "Commercial Proposal",
    shortLabel: "CP",
    codePrefix: "CP",
    description: "Business commercial proposal with pricing",
    icon: "Briefcase",
    hasBOQ: true,
    hasTimeline: true,
    hasGallery: true,
    hasSignatures: true,
    hasQR: true,
    defaultSections: ["cover", "client", "company_profile", "project", "scope_of_work", "boq", "timeline", "terms", "signatures", "qr"],
    supportedSections: ["cover", "client", "company_profile", "project", "scope_of_work", "boq", "timeline", "terms", "signatures", "qr"],
    color: "#a855f7",
  },
  PROJECT_ESTIMATE: {
    type: "PROJECT_ESTIMATE",
    name: "Project Estimate",
    label: "Project Estimate",
    shortLabel: "PE",
    codePrefix: "PE",
    description: "Preliminary project cost estimation",
    icon: "Calculator",
    hasBOQ: true,
    hasTimeline: true,
    hasGallery: false,
    hasSignatures: true,
    hasQR: false,
    defaultSections: ["cover", "client", "project", "boq", "timeline", "signatures"],
    supportedSections: ["cover", "client", "project", "boq", "timeline", "signatures"],
    color: "#ec4899",
  },
  COST_BREAKDOWN: {
    type: "COST_BREAKDOWN",
    name: "Cost Breakdown",
    label: "Cost Breakdown",
    shortLabel: "CB",
    codePrefix: "CB",
    description: "Detailed cost analysis and breakdown",
    icon: "PieChart",
    hasBOQ: true,
    hasTimeline: false,
    hasGallery: false,
    hasSignatures: true,
    hasQR: false,
    defaultSections: ["cover", "client", "boq", "signatures"],
    supportedSections: ["cover", "client", "boq", "signatures"],
    color: "#f97316",
  },
  COMPLETION_CERTIFICATE: {
    type: "COMPLETION_CERTIFICATE",
    name: "Completion Certificate",
    label: "Completion Certificate",
    shortLabel: "CC",
    codePrefix: "CC",
    description: "Project completion and handover certificate",
    icon: "Award",
    hasBOQ: false,
    hasTimeline: true,
    hasGallery: true,
    hasSignatures: true,
    hasQR: true,
    defaultSections: ["cover", "client", "project", "timeline", "gallery", "signatures", "qr"],
    supportedSections: ["cover", "client", "project", "timeline", "gallery", "signatures", "qr"],
    color: "#22c55e",
  },
  PAYMENT_RECEIPT: {
    type: "PAYMENT_RECEIPT",
    name: "Payment Receipt",
    label: "Payment Receipt",
    shortLabel: "PR",
    codePrefix: "PR",
    description: "Payment acknowledgement receipt",
    icon: "IndianRupee",
    hasBOQ: false,
    hasTimeline: false,
    hasGallery: false,
    hasSignatures: true,
    hasQR: true,
    defaultSections: ["cover", "client", "signatures", "qr"],
    supportedSections: ["cover", "client", "signatures", "qr"],
    color: "#16a34a",
  },
  DELIVERY_CHALLAN: {
    type: "DELIVERY_CHALLAN",
    name: "Material Delivery Challan",
    label: "Material Delivery Challan",
    shortLabel: "DC",
    codePrefix: "DC",
    description: "Material delivery and dispatch note",
    icon: "Truck",
    hasBOQ: true,
    hasTimeline: false,
    hasGallery: false,
    hasSignatures: true,
    hasQR: false,
    defaultSections: ["cover", "client", "boq", "signatures"],
    supportedSections: ["cover", "client", "boq", "signatures"],
    color: "#78716c",
  },
  WARRANTY_CERTIFICATE: {
    type: "WARRANTY_CERTIFICATE",
    name: "Warranty Certificate",
    label: "Warranty Certificate",
    shortLabel: "WC",
    codePrefix: "WC",
    description: "Product/service warranty certificate",
    icon: "Shield",
    hasBOQ: false,
    hasTimeline: false,
    hasGallery: false,
    hasSignatures: true,
    hasQR: true,
    defaultSections: ["cover", "client", "project", "terms", "signatures", "qr"],
    supportedSections: ["cover", "client", "project", "terms", "signatures", "qr"],
    color: "#2563eb",
  },
  AMC_AGREEMENT: {
    type: "AMC_AGREEMENT",
    name: "AMC Agreement",
    label: "AMC Agreement",
    shortLabel: "AMC",
    codePrefix: "AMC",
    description: "Annual maintenance contract agreement",
    icon: "Wrench",
    hasBOQ: true,
    hasTimeline: true,
    hasGallery: false,
    hasSignatures: true,
    hasQR: true,
    defaultSections: ["cover", "client", "project", "scope_of_work", "boq", "timeline", "terms", "signatures", "qr"],
    supportedSections: ["cover", "client", "project", "scope_of_work", "boq", "timeline", "terms", "signatures", "qr"],
    color: "#ca8a04",
  },
  SERVICE_REPORT: {
    type: "SERVICE_REPORT",
    name: "Service Report",
    label: "Service Report",
    shortLabel: "SR",
    codePrefix: "SR",
    description: "Field service and maintenance report",
    icon: "ClipboardList",
    hasBOQ: false,
    hasTimeline: false,
    hasGallery: true,
    hasSignatures: true,
    hasQR: false,
    defaultSections: ["cover", "client", "project", "gallery", "signatures"],
    supportedSections: ["cover", "client", "project", "gallery", "signatures"],
    color: "#7c3aed",
  },
  INTERNAL_DOCUMENT: {
    type: "INTERNAL_DOCUMENT",
    name: "Internal Document",
    label: "Internal Document",
    shortLabel: "INT",
    codePrefix: "INT",
    description: "Internal use document",
    icon: "Lock",
    hasBOQ: false,
    hasTimeline: false,
    hasGallery: false,
    hasSignatures: false,
    hasQR: false,
    defaultSections: ["cover", "custom"],
    supportedSections: ["cover", "custom"],
    color: "#475569",
  },
};

/** Get config for a document type */
export function getDocTypeConfig(type: DocumentType): DocumentTypeConfig {
  return DOCUMENT_TYPE_CONFIGS[type];
}

/** All document types as an ordered list */
export const DOCUMENT_TYPES = Object.values(DOCUMENT_TYPE_CONFIGS);

/** Generate a document reference code */
export function generateReference(prefix: string, number: number, year?: number): string {
  const y = year ?? new Date().getFullYear();
  return `${prefix}-${y}-${String(number).padStart(5, "0")}`;
}

/** Build default sections for a document type */
export function buildDefaultSections(type: DocumentType): DocumentSectionData[] {
  const config = DOCUMENT_TYPE_CONFIGS[type];
  return config.defaultSections.map((sectionType, index) => ({
    id: crypto.randomUUID(),
    type: sectionType,
    position: index,
    title: SECTION_LABELS[sectionType] || sectionType,
    content: {},
    visible: true,
  }));
}

/** Section display labels */
export const SECTION_LABELS: Record<SectionType, string> = {
  cover: "Cover Page",
  client: "Client Details",
  project: "Project Details",
  services: "Services",
  boq: "Bill of Quantities",
  gallery: "Project Gallery",
  timeline: "Project Timeline",
  technical_drawings: "Technical Drawings",
  signatures: "Signatures",
  qr: "QR Verification",
  terms: "Terms & Conditions",
  company_profile: "Company Profile",
  scope_of_work: "Scope of Work",
  methodology: "Execution Methodology",
  custom: "Custom Section",
};

/** Section icons (lucide names) */
export const SECTION_ICONS: Record<SectionType, string> = {
  cover: "BookOpen",
  client: "Building2",
  project: "FolderKanban",
  services: "Wrench",
  boq: "Table",
  gallery: "Images",
  timeline: "Clock",
  technical_drawings: "PenTool",
  signatures: "PenLine",
  qr: "QrCode",
  terms: "Scale",
  company_profile: "Building",
  scope_of_work: "ListChecks",
  methodology: "Workflow",
  custom: "FileEdit",
};

/** Status configurations */
export const DOCUMENT_STATUS_CONFIG: Record<DocumentStatus, { label: string; color: string; bgColor: string }> = {
  DRAFT: { label: "Draft", color: "#94a3b8", bgColor: "#1e293b" },
  PENDING_REVIEW: { label: "Pending Review", color: "#f59e0b", bgColor: "#451a03" },
  UNDER_REVIEW: { label: "Under Review", color: "#f97316", bgColor: "#431407" },
  REVISION: { label: "Revision", color: "#3b82f6", bgColor: "#172554" },
  APPROVED: { label: "Approved", color: "#22c55e", bgColor: "#052e16" },
  REJECTED: { label: "Rejected", color: "#ef4444", bgColor: "#450a0a" },
  EXPIRED: { label: "Expired", color: "#78716c", bgColor: "#1c1917" },
  CANCELLED: { label: "Cancelled", color: "#6b7280", bgColor: "#111827" },
  FINALIZED: { label: "Finalized", color: "#8b5cf6", bgColor: "#2e1065" },
  ISSUED: { label: "Issued", color: "#06b6d4", bgColor: "#083344" },
  VIEWED: { label: "Viewed", color: "#a78bfa", bgColor: "#2e1065" },
  ACCEPTED: { label: "Accepted", color: "#34d399", bgColor: "#064e3b" },
  COMPLETED: { label: "Completed", color: "#10b981", bgColor: "#022c22" },
  ARCHIVED: { label: "Archived", color: "#6b7280", bgColor: "#1f2937" },
};

import type { DocumentStatus } from "./types";
