import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Mail, Phone, UserRound } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { Reveal } from "@/components/reveal";
import { Button } from "@/components/ui/button";
import { company } from "@/lib/company";
export const metadata: Metadata={title:"Contact",description:"Contact Saini Tubewell Boring Service to discuss borewell and tubewell requirements."};
export default function Contact(){return <><PageHero eyebrow="Contact" title="Start with the requirement." text="Tell us what service you need and where the project is located. We will use that information to guide the next conversation."/><section className="bg-neutral-100 px-5 py-24 text-black lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><Reveal><p className="text-xs font-extrabold uppercase tracking-[.22em]">Project enquiries</p><h2 className="mt-5 font-display text-5xl font-bold uppercase leading-none">A clear brief gets work moving.</h2><p className="mt-7 max-w-xl leading-8 text-black/55">Call or email our team directly, or use the quote request to send the service, location and project details in one place.</p><Button asChild variant="dark" size="lg" className="mt-8"><Link href="/quote">Request a quote <ArrowRight size={17}/></Link></Button></Reveal><Reveal delay={.1} className="grid gap-px bg-black/10 sm:grid-cols-2"><a href={`tel:+91${company.phones[0]}`} className="bg-white p-8 transition hover:bg-signal"><Phone/><h3 className="mt-8 font-display text-2xl uppercase">Call us</h3><p className="mt-3 text-sm text-black/60">+91 {company.phones[0]}<br/>+91 {company.phones[1]}</p></a><a href={`mailto:${company.email}`} className="bg-white p-8 transition hover:bg-signal"><Mail/><h3 className="mt-8 font-display text-2xl uppercase">Email us</h3><p className="mt-3 break-all text-sm text-black/60">{company.email}</p></a><div className="bg-white p-8 sm:col-span-2"><UserRound/><h3 className="mt-8 font-display text-2xl uppercase">{company.managingDirector}</h3><p className="mt-3 text-sm text-black/50">Managing Director</p></div></Reveal></div></section></>}
