import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Boxes, CloudRain, Construction, Drill } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { ServiceCta, WaveDivider } from "@/components/public/site-additions";
import { pageMetadata } from "@/lib/page-metadata";

export const metadata: Metadata = pageMetadata({ title: "Services", description: "Explore borewell drilling, rainwater harvesting, material supply and tubewell construction.", path: "/services" });
const services = [["Borewell Drilling", "Precision drilling planned around access, ground conditions and water requirements.", "/borewell-drilling", Drill], ["Rainwater Harvesting", "Practical recharge systems for responsible rainwater management.", "/rainwater-harvesting", CloudRain], ["Borewell Material Supply", "Borewell components selected around durability and fit for the installation.", "/borewell-material-supply", Boxes], ["Tubewell Construction", "Coordinated execution from planning to installation and handover.", "/tubewell-construction", Construction]] as const;
export default function Services() { return <><PageHero eyebrow="Capabilities" title="Water infrastructure, one service at a time." text="Choose a service to see the process, planning points and questions we can work through with you."/><section className="bg-[#f0fdfa] px-5 py-20 text-ink lg:px-8"><div className="mx-auto grid max-w-7xl gap-5 md:grid-cols-2">{services.map(([name, text, href, Icon]) => <Link key={href} href={href} className="group rounded-2xl border border-cyan-900/15 bg-white p-8 shadow-sm transition hover:-translate-y-1 hover:border-signal"><Icon className="text-signal" size={34}/><h2 className="mt-12 font-display text-3xl uppercase text-water-dark">{name}</h2><p className="mt-4 leading-7 text-slate-600">{text}</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-signal">Explore service <ArrowRight size={16}/></span></Link>)}</div></section><WaveDivider/><ServiceCta/></>; }
